// Generated by CIRCT unknown git version

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BoomWritebackUnit(
  input          clock,
  input          reset,
  output         io_req_ready,
  input          io_req_valid,
  input  [19:0]  io_req_bits_tag,
  input  [5:0]   io_req_bits_idx,
  input  [2:0]   io_req_bits_param,
  input  [7:0]   io_req_bits_way_en,
  input          io_req_bits_voluntary,
  input          io_meta_read_ready,
  output         io_meta_read_valid,
  output [5:0]   io_meta_read_bits_idx,
  output [19:0]  io_meta_read_bits_tag,
  output         io_resp,
  output         io_idx_valid,
  output [5:0]   io_idx_bits,
  input          io_data_req_ready,
  output         io_data_req_valid,
  output [7:0]   io_data_req_bits_way_en,
  output [11:0]  io_data_req_bits_addr,
  input  [127:0] io_data_resp,
  input          io_mem_grant,
  input          io_release_ready,
  output         io_release_valid,
  output [2:0]   io_release_bits_opcode,
  output [2:0]   io_release_bits_param,
  output [31:0]  io_release_bits_address,
  output [127:0] io_release_bits_data,
  input          io_lsu_release_ready,
  output         io_lsu_release_valid,
  output [31:0]  io_lsu_release_bits_address
);

  reg  [19:0]       req_tag;
  reg  [5:0]        req_idx;
  reg  [2:0]        req_param;
  reg  [7:0]        req_way_en;
  reg               req_voluntary;
  reg  [2:0]        state;
  reg               r1_data_req_fired;
  reg               r2_data_req_fired;
  reg  [2:0]        r1_data_req_cnt;
  reg  [2:0]        r2_data_req_cnt;
  reg  [2:0]        data_req_cnt;
  reg  [127:0]      wb_buffer_0;
  reg  [127:0]      wb_buffer_1;
  reg  [127:0]      wb_buffer_2;
  reg  [127:0]      wb_buffer_3;
  reg               acked;
  wire [31:0]       r_address = {req_tag, req_idx, 6'h0};
  wire [3:0][127:0] _GEN = {{wb_buffer_3}, {wb_buffer_2}, {wb_buffer_1}, {wb_buffer_0}};
  wire              io_req_ready_0 = state == 3'h0;
  wire              _GEN_0 = state == 3'h1;
  wire              io_data_req_valid_0 = ~io_req_ready_0 & _GEN_0 & ~(data_req_cnt[2]);
  wire              _GEN_1 = r2_data_req_cnt == 3'h3;
  wire              _GEN_2 = state == 3'h2;
  wire              io_lsu_release_valid_0 = ~(io_req_ready_0 | _GEN_0) & _GEN_2;
  wire              _GEN_3 = state == 3'h3;
  wire              _GEN_4 = _GEN_0 | _GEN_2;
  wire              io_release_valid_0 = ~(io_req_ready_0 | _GEN_4) & _GEN_3 & ~(data_req_cnt[2]);
  wire              _GEN_5 = io_release_ready & io_release_valid_0;
  wire              _GEN_6 = state == 3'h4;
  wire              _GEN_7 = io_req_ready_0 & io_req_valid;
  wire              _GEN_8 = io_req_ready_0 | ~_GEN_0;
  wire              _GEN_9 = io_data_req_ready & io_data_req_valid_0 & io_meta_read_ready;
  always @(posedge clock) begin
    if (_GEN_7) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      req_tag <= io_req_bits_tag;
      req_idx <= io_req_bits_idx;
      req_param <= io_req_bits_param;
      req_way_en <= io_req_bits_way_en;
      req_voluntary <= io_req_bits_voluntary;
    end
    if (_GEN_8) begin
    end
    else begin
      r1_data_req_cnt <= _GEN_9 ? data_req_cnt : 3'h0;
      r2_data_req_cnt <= r1_data_req_cnt;
    end
    if (io_req_ready_0 | ~(_GEN_0 & r2_data_req_fired & r2_data_req_cnt[1:0] == 2'h0)) begin
    end
    else
      wb_buffer_0 <= io_data_resp;
    if (io_req_ready_0 | ~(_GEN_0 & r2_data_req_fired & r2_data_req_cnt[1:0] == 2'h1)) begin
    end
    else
      wb_buffer_1 <= io_data_resp;
    if (io_req_ready_0 | ~(_GEN_0 & r2_data_req_fired & r2_data_req_cnt[1:0] == 2'h2)) begin
    end
    else
      wb_buffer_2 <= io_data_resp;
    if (io_req_ready_0 | ~(_GEN_0 & r2_data_req_fired & (&(r2_data_req_cnt[1:0])))) begin
    end
    else
      wb_buffer_3 <= io_data_resp;
    if (reset) begin
      state <= 3'h0;
      r1_data_req_fired <= 1'h0;
      r2_data_req_fired <= 1'h0;
      data_req_cnt <= 3'h0;
      acked <= 1'h0;
    end
    else begin
      if (io_req_ready_0) begin
        if (_GEN_7) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
          state <= 3'h1;
          data_req_cnt <= 3'h0;
        end
        acked <= ~_GEN_7 & acked;
      end
      else begin
        if (_GEN_0) begin
          if (r2_data_req_fired & _GEN_1) begin
            state <= 3'h2;
            data_req_cnt <= 3'h0;
          end
          else if (_GEN_9)
            data_req_cnt <= data_req_cnt + 3'h1;
        end
        else begin
          if (_GEN_2) begin
            if (io_lsu_release_ready & io_lsu_release_valid_0)
              state <= 3'h3;
          end
          else if (_GEN_3) begin
            if (data_req_cnt == 3'h3 & _GEN_5)
              state <= {req_voluntary, 2'h0};
          end
          else if (_GEN_6 & acked)
            state <= 3'h0;
          if (_GEN_2 | ~_GEN_5) begin
          end
          else
            data_req_cnt <= data_req_cnt + 3'h1;
        end
        if (~_GEN_4)
          acked <= _GEN_3 ? io_mem_grant | acked : _GEN_6 & io_mem_grant | acked;
      end
      if (_GEN_8) begin
      end
      else begin
        r1_data_req_fired <= _GEN_9;
        r2_data_req_fired <= r1_data_req_fired;
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:18];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h13; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        req_tag = _RANDOM[5'h0][19:0];
        req_idx = _RANDOM[5'h0][25:20];
        req_param = {_RANDOM[5'h0][31:30], _RANDOM[5'h1][0]};
        req_way_en = _RANDOM[5'h1][8:1];
        req_voluntary = _RANDOM[5'h1][9];
        state = _RANDOM[5'h1][12:10];
        r1_data_req_fired = _RANDOM[5'h1][13];
        r2_data_req_fired = _RANDOM[5'h1][14];
        r1_data_req_cnt = _RANDOM[5'h1][17:15];
        r2_data_req_cnt = _RANDOM[5'h1][20:18];
        data_req_cnt = _RANDOM[5'h1][23:21];
        wb_buffer_0 = {_RANDOM[5'h2], _RANDOM[5'h3], _RANDOM[5'h4], _RANDOM[5'h5]};
        wb_buffer_1 = {_RANDOM[5'h6], _RANDOM[5'h7], _RANDOM[5'h8], _RANDOM[5'h9]};
        wb_buffer_2 = {_RANDOM[5'hA], _RANDOM[5'hB], _RANDOM[5'hC], _RANDOM[5'hD]};
        wb_buffer_3 = {_RANDOM[5'hE], _RANDOM[5'hF], _RANDOM[5'h10], _RANDOM[5'h11]};
        acked = _RANDOM[5'h12][0];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_req_ready = io_req_ready_0;
  assign io_meta_read_valid = io_data_req_valid_0;
  assign io_meta_read_bits_idx = req_idx;
  assign io_meta_read_bits_tag = req_tag;
  assign io_resp = ~io_req_ready_0 & _GEN_0 & r2_data_req_fired & _GEN_1;
  assign io_idx_valid = |state;
  assign io_idx_bits = req_idx;
  assign io_data_req_valid = io_data_req_valid_0;
  assign io_data_req_bits_way_en = req_way_en;
  assign io_data_req_bits_addr = {req_idx, data_req_cnt[1:0], 4'h0};
  assign io_release_valid = io_release_valid_0;
  assign io_release_bits_opcode = {1'h1, req_voluntary, 1'h1};
  assign io_release_bits_param = req_param;
  assign io_release_bits_address = r_address;
  assign io_release_bits_data = _GEN[data_req_cnt[1:0]];
  assign io_lsu_release_valid = io_lsu_release_valid_0;
  assign io_lsu_release_bits_address = r_address;
endmodule

