// Generated by CIRCT unknown git version
module ebtb(
  input  [6:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [39:0] R0_data,
  input  [6:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [39:0] W0_data
);

  ebtb_ext ebtb_ext (
    .R0_addr (R0_addr),
    .R0_en   (R0_en),
    .R0_clk  (R0_clk),
    .R0_data (R0_data),
    .W0_addr (W0_addr),
    .W0_en   (W0_en),
    .W0_clk  (W0_clk),
    .W0_data (W0_data)
  );
endmodule

