// Generated by CIRCT unknown git version

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module FDivSqrtUnit(
  input         clock,
  input         reset,
  output        io_req_ready,
  input         io_req_valid,
  input  [6:0]  io_req_bits_uop_uopc,
  input  [19:0] io_req_bits_uop_br_mask,
  input  [19:0] io_req_bits_uop_imm_packed,
  input  [6:0]  io_req_bits_uop_rob_idx,
  input  [6:0]  io_req_bits_uop_pdst,
  input         io_req_bits_uop_is_amo,
  input         io_req_bits_uop_uses_ldq,
  input         io_req_bits_uop_uses_stq,
  input  [1:0]  io_req_bits_uop_dst_rtype,
  input         io_req_bits_uop_fp_val,
  input  [64:0] io_req_bits_rs1_data,
  input  [64:0] io_req_bits_rs2_data,
  input         io_req_bits_kill,
  input         io_resp_ready,
  output        io_resp_valid,
  output [6:0]  io_resp_bits_uop_rob_idx,
  output [6:0]  io_resp_bits_uop_pdst,
  output        io_resp_bits_uop_is_amo,
  output        io_resp_bits_uop_uses_ldq,
  output        io_resp_bits_uop_uses_stq,
  output [1:0]  io_resp_bits_uop_dst_rtype,
  output        io_resp_bits_uop_fp_val,
  output [64:0] io_resp_bits_data,
  output        io_resp_bits_fflags_valid,
  output [6:0]  io_resp_bits_fflags_bits_uop_rob_idx,
  output [4:0]  io_resp_bits_fflags_bits_flags,
  input  [19:0] io_brupdate_b1_resolve_mask,
  input  [19:0] io_brupdate_b1_mispredict_mask,
  input  [2:0]  io_fcsr_rm
);

  wire        output_buffer_available;
  wire [32:0] _downvert_d2s_io_out;
  wire [4:0]  _downvert_d2s_io_exceptionFlags;
  wire        _divsqrt_io_inReady_div;
  wire        _divsqrt_io_inReady_sqrt;
  wire        _divsqrt_io_outValid_div;
  wire        _divsqrt_io_outValid_sqrt;
  wire [64:0] _divsqrt_io_out;
  wire [4:0]  _divsqrt_io_exceptionFlags;
  wire [64:0] _in2_upconvert_s2d_io_out;
  wire [64:0] _in1_upconvert_s2d_io_out;
  wire [1:0]  _fdiv_decoder_io_sigs_typeTagIn;
  wire        _fdiv_decoder_io_sigs_div;
  wire        _fdiv_decoder_io_sigs_sqrt;
  reg         r_buffer_val;
  reg  [19:0] r_buffer_req_uop_br_mask;
  reg  [6:0]  r_buffer_req_uop_rob_idx;
  reg  [6:0]  r_buffer_req_uop_pdst;
  reg         r_buffer_req_uop_is_amo;
  reg         r_buffer_req_uop_uses_ldq;
  reg         r_buffer_req_uop_uses_stq;
  reg  [1:0]  r_buffer_req_uop_dst_rtype;
  reg         r_buffer_req_uop_fp_val;
  reg  [1:0]  r_buffer_fin_typeTagIn;
  reg         r_buffer_fin_div;
  reg         r_buffer_fin_sqrt;
  reg  [2:0]  r_buffer_fin_rm;
  reg  [64:0] r_buffer_fin_in1;
  reg  [64:0] r_buffer_fin_in2;
  reg         r_divsqrt_val;
  reg         r_divsqrt_killed;
  reg  [1:0]  r_divsqrt_fin_typeTagIn;
  reg  [2:0]  r_divsqrt_fin_rm;
  reg  [19:0] r_divsqrt_uop_br_mask;
  reg  [6:0]  r_divsqrt_uop_rob_idx;
  reg  [6:0]  r_divsqrt_uop_pdst;
  reg         r_divsqrt_uop_is_amo;
  reg         r_divsqrt_uop_uses_ldq;
  reg         r_divsqrt_uop_uses_stq;
  reg  [1:0]  r_divsqrt_uop_dst_rtype;
  reg         r_divsqrt_uop_fp_val;
  wire        divsqrt_io_inValid = r_buffer_val & (r_buffer_fin_div | r_buffer_fin_sqrt) & ~r_divsqrt_val & output_buffer_available;
  reg         r_out_val;
  reg  [19:0] r_out_uop_br_mask;
  reg  [6:0]  r_out_uop_rob_idx;
  reg  [6:0]  r_out_uop_pdst;
  reg         r_out_uop_is_amo;
  reg         r_out_uop_uses_ldq;
  reg         r_out_uop_uses_stq;
  reg  [1:0]  r_out_uop_dst_rtype;
  reg         r_out_uop_fp_val;
  reg  [4:0]  r_out_flags_double;
  reg  [64:0] r_out_wdata_double;
  assign output_buffer_available = ~r_out_val;
  wire [19:0] _io_resp_valid_T = io_brupdate_b1_mispredict_mask & r_out_uop_br_mask;
  wire        _GEN = _divsqrt_io_outValid_div | _divsqrt_io_outValid_sqrt;
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (~reset & r_buffer_val & io_req_valid) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [fdiv] a request is incoming while the buffer is already full.\n    at fdiv.scala:138 assert (!(r_buffer_val && io.req.valid), \"[fdiv] a request is incoming while the buffer is already full.\")\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (_GEN & ~reset & ~r_divsqrt_val) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [fdiv] a response is being generated for no request.\n    at fdiv.scala:205 assert (r_divsqrt_val, \"[fdiv] a response is being generated for no request.\")\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & r_out_val & _GEN) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [fdiv] Buffered output being overwritten by another output from the fdiv/fsqrt unit.\n    at fdiv.scala:208 assert (!(r_out_val && (divsqrt.io.outValid_div || divsqrt.io.outValid_sqrt)),\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _io_resp_bits_data_T = r_divsqrt_fin_typeTagIn == 2'h0;
  wire        io_resp_valid_0 = r_out_val & _io_resp_valid_T == 20'h0;
  wire        _GEN_0 = _fdiv_decoder_io_sigs_typeTagIn == 2'h0;
  wire [19:0] _r_divsqrt_killed_T_4 = io_brupdate_b1_mispredict_mask & r_buffer_req_uop_br_mask;
  wire        _GEN_1 = io_req_valid & (io_brupdate_b1_mispredict_mask & io_req_bits_uop_br_mask) == 20'h0 & ~io_req_bits_kill;
  wire [19:0] _r_out_val_T_1 = io_brupdate_b1_mispredict_mask & r_divsqrt_uop_br_mask;
  wire        _GEN_2 = divsqrt_io_inValid & (r_buffer_fin_sqrt ? _divsqrt_io_inReady_sqrt : _divsqrt_io_inReady_div);
  always @(posedge clock) begin
    if (reset) begin
      r_buffer_val <= 1'h0;
      r_divsqrt_val <= 1'h0;
      r_out_val <= 1'h0;
    end
    else begin
      r_buffer_val <= ~_GEN_2 & (_GEN_1 | _r_divsqrt_killed_T_4 == 20'h0 & ~io_req_bits_kill & r_buffer_val);
      r_divsqrt_val <= ~_GEN & (_GEN_2 | r_divsqrt_val);
      r_out_val <= _GEN ? ~r_divsqrt_killed & _r_out_val_T_1 == 20'h0 & ~io_req_bits_kill : ~((|{io_resp_ready, _io_resp_valid_T}) | io_req_bits_kill) & r_out_val;
    end
    r_buffer_req_uop_br_mask <= _GEN_1 ? io_req_bits_uop_br_mask & ~io_brupdate_b1_resolve_mask : r_buffer_req_uop_br_mask & ~io_brupdate_b1_resolve_mask;
    if (_GEN_1) begin
      r_buffer_req_uop_rob_idx <= io_req_bits_uop_rob_idx;
      r_buffer_req_uop_pdst <= io_req_bits_uop_pdst;
      r_buffer_req_uop_is_amo <= io_req_bits_uop_is_amo;
      r_buffer_req_uop_uses_ldq <= io_req_bits_uop_uses_ldq;
      r_buffer_req_uop_uses_stq <= io_req_bits_uop_uses_stq;
      r_buffer_req_uop_dst_rtype <= io_req_bits_uop_dst_rtype;
      r_buffer_req_uop_fp_val <= io_req_bits_uop_fp_val;
      r_buffer_fin_typeTagIn <= _fdiv_decoder_io_sigs_typeTagIn;
      r_buffer_fin_div <= _fdiv_decoder_io_sigs_div;
      r_buffer_fin_sqrt <= _fdiv_decoder_io_sigs_sqrt;
      r_buffer_fin_rm <= (&(io_req_bits_uop_imm_packed[2:0])) ? io_fcsr_rm : io_req_bits_uop_imm_packed[2:0];
      r_buffer_fin_in1 <= _GEN_0 ? _in1_upconvert_s2d_io_out : io_req_bits_rs1_data;
      r_buffer_fin_in2 <= _GEN_0 ? _in2_upconvert_s2d_io_out : io_req_bits_rs2_data;
    end
    r_divsqrt_killed <= _GEN_2 ? (|_r_divsqrt_killed_T_4) | io_req_bits_kill : (|{r_divsqrt_killed, _r_out_val_T_1}) | io_req_bits_kill;
    if (_GEN_2) begin
      r_divsqrt_fin_typeTagIn <= r_buffer_fin_typeTagIn;
      r_divsqrt_fin_rm <= r_buffer_fin_rm;
      r_divsqrt_uop_rob_idx <= r_buffer_req_uop_rob_idx;
      r_divsqrt_uop_pdst <= r_buffer_req_uop_pdst;
      r_divsqrt_uop_is_amo <= r_buffer_req_uop_is_amo;
      r_divsqrt_uop_uses_ldq <= r_buffer_req_uop_uses_ldq;
      r_divsqrt_uop_uses_stq <= r_buffer_req_uop_uses_stq;
      r_divsqrt_uop_dst_rtype <= r_buffer_req_uop_dst_rtype;
      r_divsqrt_uop_fp_val <= r_buffer_req_uop_fp_val;
    end
    r_divsqrt_uop_br_mask <= _GEN_2 ? r_buffer_req_uop_br_mask & ~io_brupdate_b1_resolve_mask : r_divsqrt_uop_br_mask & ~io_brupdate_b1_resolve_mask;
    r_out_uop_br_mask <= _GEN ? r_divsqrt_uop_br_mask & ~io_brupdate_b1_resolve_mask : r_out_uop_br_mask & ~io_brupdate_b1_resolve_mask;
    if (_GEN) begin
      r_out_uop_rob_idx <= r_divsqrt_uop_rob_idx;
      r_out_uop_pdst <= r_divsqrt_uop_pdst;
      r_out_uop_is_amo <= r_divsqrt_uop_is_amo;
      r_out_uop_uses_ldq <= r_divsqrt_uop_uses_ldq;
      r_out_uop_uses_stq <= r_divsqrt_uop_uses_stq;
      r_out_uop_dst_rtype <= r_divsqrt_uop_dst_rtype;
      r_out_uop_fp_val <= r_divsqrt_uop_fp_val;
      r_out_flags_double <= _divsqrt_io_exceptionFlags;
      r_out_wdata_double <= ({65{_divsqrt_io_out[63:61] != 3'h7}} | 65'h1EFEFFFFFFFFFFFFF) & _divsqrt_io_out;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:61];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h3E; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        r_buffer_val = _RANDOM[6'h0][0];
        r_buffer_req_uop_br_mask = {_RANDOM[6'h4][31:30], _RANDOM[6'h5][17:0]};
        r_buffer_req_uop_rob_idx = _RANDOM[6'h7][11:5];
        r_buffer_req_uop_pdst = _RANDOM[6'h7][30:24];
        r_buffer_req_uop_is_amo = _RANDOM[6'hB][17];
        r_buffer_req_uop_uses_ldq = _RANDOM[6'hB][18];
        r_buffer_req_uop_uses_stq = _RANDOM[6'hB][19];
        r_buffer_req_uop_dst_rtype = _RANDOM[6'hC][18:17];
        r_buffer_req_uop_fp_val = _RANDOM[6'hC][24];
        r_buffer_fin_typeTagIn = _RANDOM[6'h13][16:15];
        r_buffer_fin_div = _RANDOM[6'h13][23];
        r_buffer_fin_sqrt = _RANDOM[6'h13][24];
        r_buffer_fin_rm = _RANDOM[6'h13][29:27];
        r_buffer_fin_in1 = {_RANDOM[6'h14][31:4], _RANDOM[6'h15], _RANDOM[6'h16][4:0]};
        r_buffer_fin_in2 = {_RANDOM[6'h16][31:5], _RANDOM[6'h17], _RANDOM[6'h18][5:0]};
        r_divsqrt_val = _RANDOM[6'h1A][7];
        r_divsqrt_killed = _RANDOM[6'h1A][8];
        r_divsqrt_fin_typeTagIn = _RANDOM[6'h1A][17:16];
        r_divsqrt_fin_rm = _RANDOM[6'h1A][30:28];
        r_divsqrt_uop_br_mask = _RANDOM[6'h26][24:5];
        r_divsqrt_uop_rob_idx = _RANDOM[6'h28][18:12];
        r_divsqrt_uop_pdst = {_RANDOM[6'h28][31], _RANDOM[6'h29][5:0]};
        r_divsqrt_uop_is_amo = _RANDOM[6'h2C][24];
        r_divsqrt_uop_uses_ldq = _RANDOM[6'h2C][25];
        r_divsqrt_uop_uses_stq = _RANDOM[6'h2C][26];
        r_divsqrt_uop_dst_rtype = _RANDOM[6'h2D][25:24];
        r_divsqrt_uop_fp_val = _RANDOM[6'h2D][31];
        r_out_val = _RANDOM[6'h2E][10];
        r_out_uop_br_mask = _RANDOM[6'h33][27:8];
        r_out_uop_rob_idx = _RANDOM[6'h35][21:15];
        r_out_uop_pdst = _RANDOM[6'h36][8:2];
        r_out_uop_is_amo = _RANDOM[6'h39][27];
        r_out_uop_uses_ldq = _RANDOM[6'h39][28];
        r_out_uop_uses_stq = _RANDOM[6'h39][29];
        r_out_uop_dst_rtype = _RANDOM[6'h3A][28:27];
        r_out_uop_fp_val = _RANDOM[6'h3B][2];
        r_out_flags_double = _RANDOM[6'h3B][17:13];
        r_out_wdata_double = {_RANDOM[6'h3B][31:18], _RANDOM[6'h3C], _RANDOM[6'h3D][18:0]};
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  UOPCodeFDivDecoder fdiv_decoder (
    .io_uopc           (io_req_bits_uop_uopc),
    .io_sigs_typeTagIn (_fdiv_decoder_io_sigs_typeTagIn),
    .io_sigs_div       (_fdiv_decoder_io_sigs_div),
    .io_sigs_sqrt      (_fdiv_decoder_io_sigs_sqrt)
  );
  RecFNToRecFN_1 in1_upconvert_s2d (
    .io_in  ({io_req_bits_rs1_data[31], io_req_bits_rs1_data[52], io_req_bits_rs1_data[30:0]} | ((&(io_req_bits_rs1_data[64:60])) ? 33'h0 : 33'hE0400000)),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :372:{26,31}]
    .io_out (_in1_upconvert_s2d_io_out)
  );
  RecFNToRecFN_1 in2_upconvert_s2d (
    .io_in  ({io_req_bits_rs2_data[31], io_req_bits_rs2_data[52], io_req_bits_rs2_data[30:0]} | ((&(io_req_bits_rs2_data[64:60])) ? 33'h0 : 33'hE0400000)),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :372:{26,31}]
    .io_out (_in2_upconvert_s2d_io_out)
  );
  DivSqrtRecF64 divsqrt (
    .clock             (clock),
    .reset             (reset),
    .io_inReady_div    (_divsqrt_io_inReady_div),
    .io_inReady_sqrt   (_divsqrt_io_inReady_sqrt),
    .io_inValid        (divsqrt_io_inValid),
    .io_sqrtOp         (r_buffer_fin_sqrt),
    .io_a              (r_buffer_fin_in1),
    .io_b              (r_buffer_fin_sqrt ? r_buffer_fin_in1 : r_buffer_fin_in2),
    .io_roundingMode   (r_buffer_fin_rm),
    .io_outValid_div   (_divsqrt_io_outValid_div),
    .io_outValid_sqrt  (_divsqrt_io_outValid_sqrt),
    .io_out            (_divsqrt_io_out),
    .io_exceptionFlags (_divsqrt_io_exceptionFlags)
  );
  RecFNToRecFN downvert_d2s (
    .io_in             (r_out_wdata_double),
    .io_roundingMode   (r_divsqrt_fin_rm),
    .io_detectTininess (1'h0),
    .io_out            (_downvert_d2s_io_out),
    .io_exceptionFlags (_downvert_d2s_io_exceptionFlags)
  );
  assign io_req_ready = ~r_buffer_val;
  assign io_resp_valid = io_resp_valid_0;
  assign io_resp_bits_uop_rob_idx = r_out_uop_rob_idx;
  assign io_resp_bits_uop_pdst = r_out_uop_pdst;
  assign io_resp_bits_uop_is_amo = r_out_uop_is_amo;
  assign io_resp_bits_uop_uses_ldq = r_out_uop_uses_ldq;
  assign io_resp_bits_uop_uses_stq = r_out_uop_uses_stq;
  assign io_resp_bits_uop_dst_rtype = r_out_uop_dst_rtype;
  assign io_resp_bits_uop_fp_val = r_out_uop_fp_val;
  assign io_resp_bits_data = _io_resp_bits_data_T ? {12'hFFF, _downvert_d2s_io_out[31], 20'hFFFFF, _downvert_d2s_io_out[32], _downvert_d2s_io_out[30:0]} : r_out_wdata_double;
  assign io_resp_bits_fflags_valid = io_resp_valid_0;
  assign io_resp_bits_fflags_bits_uop_rob_idx = r_out_uop_rob_idx;
  assign io_resp_bits_fflags_bits_flags = r_out_flags_double | (_io_resp_bits_data_T ? _downvert_d2s_io_exceptionFlags : 5'h0);
endmodule

