// Generated by CIRCT unknown git version

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BoomProbeUnit(
  input         clock,
  input         reset,
  output        io_req_ready,
  input         io_req_valid,
  input  [1:0]  io_req_bits_param,
  input  [3:0]  io_req_bits_size,
  input  [3:0]  io_req_bits_source,
  input  [31:0] io_req_bits_address,
  input         io_rep_ready,
  output        io_rep_valid,
  output [2:0]  io_rep_bits_param,
  output [3:0]  io_rep_bits_size,
  output [3:0]  io_rep_bits_source,
  output [31:0] io_rep_bits_address,
  input         io_meta_read_ready,
  output        io_meta_read_valid,
  output [5:0]  io_meta_read_bits_idx,
  output [19:0] io_meta_read_bits_tag,
  input         io_meta_write_ready,
  output        io_meta_write_valid,
  output [5:0]  io_meta_write_bits_idx,
  output [7:0]  io_meta_write_bits_way_en,
  output [1:0]  io_meta_write_bits_data_coh_state,
  output [19:0] io_meta_write_bits_data_tag,
  input         io_wb_req_ready,
  output        io_wb_req_valid,
  output [19:0] io_wb_req_bits_tag,
  output [5:0]  io_wb_req_bits_idx,
  output [2:0]  io_wb_req_bits_param,
  output [7:0]  io_wb_req_bits_way_en,
  input  [7:0]  io_way_en,
  input         io_wb_rdy,
  input         io_mshr_rdy,
  output        io_mshr_wb_rdy,
  input  [1:0]  io_block_state_state,
  input         io_lsu_release_ready,
  output        io_lsu_release_valid,
  output [31:0] io_lsu_release_bits_address,
  output        io_state_valid,
  output [39:0] io_state_bits
);

  reg  [3:0]       state;
  reg  [1:0]       req_param;
  reg  [3:0]       req_size;
  reg  [3:0]       req_source;
  reg  [31:0]      req_address;
  reg  [7:0]       way_en;
  reg  [1:0]       old_coh_state;
  wire [3:0]       _r_T = {req_param, (|way_en) ? old_coh_state : 2'h0};
  wire             _r_T_26 = _r_T == 4'hB;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_29 = _r_T == 4'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_33 = _r_T == 4'h5;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_37 = _r_T == 4'h6;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_41 = _r_T == 4'h7;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_45 = _r_T == 4'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_49 = _r_T == 4'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_53 = _r_T == 4'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_57 = _r_T == 4'h3;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _GEN = _r_T_57 | _r_T_53;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:38:36, :56:20]
  wire [2:0]       report_param = _GEN ? 3'h3 : _r_T_49 ? 3'h4 : _r_T_45 ? 3'h5 : _r_T_41 | _r_T_37 ? 3'h0 : _r_T_33 ? 3'h4 : _r_T_29 ? 3'h5 : _r_T_26 | _r_T == 4'hA ? 3'h1 : _r_T == 4'h9 ? 3'h2 : _r_T == 4'h8 ? 3'h5 : 3'h0;
  wire             io_req_ready_0 = state == 4'h0;
  wire             io_rep_valid_0 = state == 4'h6;
  wire             io_meta_read_valid_0 = state == 4'h1;
  wire             io_meta_write_valid_0 = state == 4'h9;
  wire             io_wb_req_valid_0 = state == 4'h7;
  wire             io_lsu_release_valid_0 = state == 4'h5;
  wire             _GEN_0 = io_req_ready_0 & io_req_valid;
  wire [15:0][3:0] _GEN_1 = {{state}, {state}, {state}, {state}, {state}, {4'h0}, {io_meta_write_ready & io_meta_write_valid_0 ? 4'hA : state}, {io_wb_req_ready ? 4'h9 : state}, {io_wb_req_ready & io_wb_req_valid_0 ? 4'h8 : state}, {io_rep_ready ? ((|way_en) ? 4'h9 : 4'h0) : state}, {io_lsu_release_ready & io_lsu_release_valid_0 ? 4'h6 : state}, {{2'h1, (|way_en) & (_r_T_57 | ~(_r_T_53 | _r_T_49 | _r_T_45) & (_r_T_41 | ~(_r_T_37 | _r_T_33 | _r_T_29) & _r_T_26)), 1'h1}}, {io_mshr_rdy & io_wb_rdy ? 4'h4 : 4'h1}, {4'h3}, {io_meta_read_ready & io_meta_read_valid_0 ? 4'h2 : state}, {_GEN_0 ? 4'h1 : state}};
  always @(posedge clock) begin
    if (reset)
      state <= 4'h0;
    else
      state <= _GEN_1[state];
    if (_GEN_0) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      req_param <= io_req_bits_param;
      req_size <= io_req_bits_size;
      req_source <= io_req_bits_source;
      req_address <= io_req_bits_address;
    end
    if (io_req_ready_0 | io_meta_read_valid_0 | state == 4'h2 | state != 4'h3) begin
    end
    else begin
      way_en <= io_way_en;
      old_coh_state <= io_block_state_state;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:6];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        state = _RANDOM[3'h0][3:0];
        req_param = _RANDOM[3'h0][8:7];
        req_size = _RANDOM[3'h0][12:9];
        req_source = _RANDOM[3'h0][16:13];
        req_address = {_RANDOM[3'h0][31:17], _RANDOM[3'h1][16:0]};
        way_en = _RANDOM[3'h6][9:2];
        old_coh_state = _RANDOM[3'h6][11:10];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_req_ready = io_req_ready_0;
  assign io_rep_valid = io_rep_valid_0;
  assign io_rep_bits_param = report_param;
  assign io_rep_bits_size = req_size;
  assign io_rep_bits_source = req_source;
  assign io_rep_bits_address = req_address;
  assign io_meta_read_valid = io_meta_read_valid_0;
  assign io_meta_read_bits_idx = req_address[11:6];
  assign io_meta_read_bits_tag = req_address[31:12];
  assign io_meta_write_valid = io_meta_write_valid_0;
  assign io_meta_write_bits_idx = req_address[11:6];
  assign io_meta_write_bits_way_en = way_en;
  assign io_meta_write_bits_data_coh_state = _GEN ? 2'h2 : _r_T_49 ? 2'h1 : _r_T_45 ? 2'h0 : {1'h0, _r_T_41 | _r_T_37 | _r_T_33};
  assign io_meta_write_bits_data_tag = req_address[31:12];
  assign io_wb_req_valid = io_wb_req_valid_0;
  assign io_wb_req_bits_tag = req_address[31:12];
  assign io_wb_req_bits_idx = req_address[11:6];
  assign io_wb_req_bits_param = report_param;
  assign io_wb_req_bits_way_en = way_en;
  assign io_mshr_wb_rdy = ~(io_rep_valid_0 | io_wb_req_valid_0 | state == 4'h8 | io_meta_write_valid_0 | state == 4'hA);
  assign io_lsu_release_valid = io_lsu_release_valid_0;
  assign io_lsu_release_bits_address = req_address;
  assign io_state_valid = |state;
  assign io_state_bits = {8'h0, req_address};
endmodule

