// Generated by CIRCT unknown git version

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BranchKillableQueue_8(
  input         clock,
  input         reset,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [6:0]  io_enq_bits_uop_uopc,
  input  [31:0] io_enq_bits_uop_inst,
  input  [31:0] io_enq_bits_uop_debug_inst,
  input         io_enq_bits_uop_is_rvc,
  input  [39:0] io_enq_bits_uop_debug_pc,
  input  [2:0]  io_enq_bits_uop_iq_type,
  input  [9:0]  io_enq_bits_uop_fu_code,
  input  [3:0]  io_enq_bits_uop_ctrl_br_type,
  input  [1:0]  io_enq_bits_uop_ctrl_op1_sel,
  input  [2:0]  io_enq_bits_uop_ctrl_op2_sel,
  input  [2:0]  io_enq_bits_uop_ctrl_imm_sel,
  input  [4:0]  io_enq_bits_uop_ctrl_op_fcn,
  input         io_enq_bits_uop_ctrl_fcn_dw,
  input  [2:0]  io_enq_bits_uop_ctrl_csr_cmd,
  input         io_enq_bits_uop_ctrl_is_load,
  input         io_enq_bits_uop_ctrl_is_sta,
  input         io_enq_bits_uop_ctrl_is_std,
  input  [1:0]  io_enq_bits_uop_iw_state,
  input         io_enq_bits_uop_iw_p1_poisoned,
  input         io_enq_bits_uop_iw_p2_poisoned,
  input         io_enq_bits_uop_is_br,
  input         io_enq_bits_uop_is_jalr,
  input         io_enq_bits_uop_is_jal,
  input         io_enq_bits_uop_is_sfb,
  input  [19:0] io_enq_bits_uop_br_mask,
  input  [4:0]  io_enq_bits_uop_br_tag,
  input  [5:0]  io_enq_bits_uop_ftq_idx,
  input         io_enq_bits_uop_edge_inst,
  input  [5:0]  io_enq_bits_uop_pc_lob,
  input         io_enq_bits_uop_taken,
  input  [19:0] io_enq_bits_uop_imm_packed,
  input  [11:0] io_enq_bits_uop_csr_addr,
  input  [6:0]  io_enq_bits_uop_rob_idx,
  input  [4:0]  io_enq_bits_uop_ldq_idx,
  input  [4:0]  io_enq_bits_uop_stq_idx,
  input  [1:0]  io_enq_bits_uop_rxq_idx,
  input  [6:0]  io_enq_bits_uop_pdst,
  input  [6:0]  io_enq_bits_uop_prs1,
  input  [6:0]  io_enq_bits_uop_prs2,
  input  [6:0]  io_enq_bits_uop_prs3,
  input  [5:0]  io_enq_bits_uop_ppred,
  input         io_enq_bits_uop_prs1_busy,
  input         io_enq_bits_uop_prs2_busy,
  input         io_enq_bits_uop_prs3_busy,
  input         io_enq_bits_uop_ppred_busy,
  input  [6:0]  io_enq_bits_uop_stale_pdst,
  input         io_enq_bits_uop_exception,
  input  [63:0] io_enq_bits_uop_exc_cause,
  input         io_enq_bits_uop_bypassable,
  input  [4:0]  io_enq_bits_uop_mem_cmd,
  input  [1:0]  io_enq_bits_uop_mem_size,
  input         io_enq_bits_uop_mem_signed,
  input         io_enq_bits_uop_is_fence,
  input         io_enq_bits_uop_is_fencei,
  input         io_enq_bits_uop_is_amo,
  input         io_enq_bits_uop_uses_ldq,
  input         io_enq_bits_uop_uses_stq,
  input         io_enq_bits_uop_is_sys_pc2epc,
  input         io_enq_bits_uop_is_unique,
  input         io_enq_bits_uop_flush_on_commit,
  input         io_enq_bits_uop_ldst_is_rs1,
  input  [5:0]  io_enq_bits_uop_ldst,
  input  [5:0]  io_enq_bits_uop_lrs1,
  input  [5:0]  io_enq_bits_uop_lrs2,
  input  [5:0]  io_enq_bits_uop_lrs3,
  input         io_enq_bits_uop_ldst_val,
  input  [1:0]  io_enq_bits_uop_dst_rtype,
  input  [1:0]  io_enq_bits_uop_lrs1_rtype,
  input  [1:0]  io_enq_bits_uop_lrs2_rtype,
  input         io_enq_bits_uop_frs3_en,
  input         io_enq_bits_uop_fp_val,
  input         io_enq_bits_uop_fp_single,
  input         io_enq_bits_uop_xcpt_pf_if,
  input         io_enq_bits_uop_xcpt_ae_if,
  input         io_enq_bits_uop_xcpt_ma_if,
  input         io_enq_bits_uop_bp_debug_if,
  input         io_enq_bits_uop_bp_xcpt_if,
  input  [1:0]  io_enq_bits_uop_debug_fsrc,
  input  [1:0]  io_enq_bits_uop_debug_tsrc,
  input  [63:0] io_enq_bits_data,
  input         io_enq_bits_is_hella,
  input         io_deq_ready,
  output        io_deq_valid,
  output [19:0] io_deq_bits_uop_br_mask,
  output [4:0]  io_deq_bits_uop_ldq_idx,
  output [4:0]  io_deq_bits_uop_stq_idx,
  output        io_deq_bits_uop_is_amo,
  output        io_deq_bits_uop_uses_ldq,
  output        io_deq_bits_uop_uses_stq,
  output [63:0] io_deq_bits_data,
  output        io_deq_bits_is_hella,
  input  [19:0] io_brupdate_b1_resolve_mask,
  input  [19:0] io_brupdate_b1_mispredict_mask,
  input         io_flush
);

  wire [64:0]      _ram_ext_R0_data;
  reg              valids_0;
  reg              valids_1;
  reg              valids_2;
  reg              valids_3;
  reg  [19:0]      uops_0_br_mask;
  reg  [4:0]       uops_0_ldq_idx;
  reg  [4:0]       uops_0_stq_idx;
  reg              uops_0_is_amo;
  reg              uops_0_uses_ldq;
  reg              uops_0_uses_stq;
  reg  [19:0]      uops_1_br_mask;
  reg  [4:0]       uops_1_ldq_idx;
  reg  [4:0]       uops_1_stq_idx;
  reg              uops_1_is_amo;
  reg              uops_1_uses_ldq;
  reg              uops_1_uses_stq;
  reg  [19:0]      uops_2_br_mask;
  reg  [4:0]       uops_2_ldq_idx;
  reg  [4:0]       uops_2_stq_idx;
  reg              uops_2_is_amo;
  reg              uops_2_uses_ldq;
  reg              uops_2_uses_stq;
  reg  [19:0]      uops_3_br_mask;
  reg  [4:0]       uops_3_ldq_idx;
  reg  [4:0]       uops_3_stq_idx;
  reg              uops_3_is_amo;
  reg              uops_3_uses_ldq;
  reg              uops_3_uses_stq;
  reg  [1:0]       enq_ptr_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg  [1:0]       deq_ptr_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg              maybe_full;
  wire             ptr_match = enq_ptr_value == deq_ptr_value;
  wire             io_empty = ptr_match & ~maybe_full;
  wire             full = ptr_match & maybe_full;
  wire             do_enq = ~full & io_enq_valid;
  wire [3:0]       _GEN = {{valids_3}, {valids_2}, {valids_1}, {valids_0}};
  wire             _GEN_0 = _GEN[deq_ptr_value];
  wire [3:0][19:0] _GEN_1 = {{uops_3_br_mask}, {uops_2_br_mask}, {uops_1_br_mask}, {uops_0_br_mask}};
  wire [19:0]      out_uop_br_mask = _GEN_1[deq_ptr_value];
  wire [3:0][4:0]  _GEN_2 = {{uops_3_ldq_idx}, {uops_2_ldq_idx}, {uops_1_ldq_idx}, {uops_0_ldq_idx}};
  wire [3:0][4:0]  _GEN_3 = {{uops_3_stq_idx}, {uops_2_stq_idx}, {uops_1_stq_idx}, {uops_0_stq_idx}};
  wire [3:0]       _GEN_4 = {{uops_3_is_amo}, {uops_2_is_amo}, {uops_1_is_amo}, {uops_0_is_amo}};
  wire [3:0]       _GEN_5 = {{uops_3_uses_ldq}, {uops_2_uses_ldq}, {uops_1_uses_ldq}, {uops_0_uses_ldq}};
  wire             out_uop_uses_ldq = _GEN_5[deq_ptr_value];
  wire [3:0]       _GEN_6 = {{uops_3_uses_stq}, {uops_2_uses_stq}, {uops_1_uses_stq}, {uops_0_uses_stq}};
  wire             do_deq = (io_deq_ready | ~_GEN_0) & ~io_empty;
  wire             _GEN_7 = enq_ptr_value == 2'h0;
  wire             _GEN_8 = do_enq & _GEN_7;
  wire             _GEN_9 = enq_ptr_value == 2'h1;
  wire             _GEN_10 = do_enq & _GEN_9;
  wire             _GEN_11 = enq_ptr_value == 2'h2;
  wire             _GEN_12 = do_enq & _GEN_11;
  wire             _GEN_13 = do_enq & (&enq_ptr_value);
  wire [19:0]      _uops_br_mask_T_1 = io_enq_bits_uop_br_mask & ~io_brupdate_b1_resolve_mask;
  always @(posedge clock) begin
    if (reset) begin
      valids_0 <= 1'h0;
      valids_1 <= 1'h0;
      valids_2 <= 1'h0;
      valids_3 <= 1'h0;
      enq_ptr_value <= 2'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
      deq_ptr_value <= 2'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
      maybe_full <= 1'h0;
    end
    else begin
      valids_0 <= ~(do_deq & deq_ptr_value == 2'h0) & (_GEN_8 | valids_0 & (io_brupdate_b1_mispredict_mask & uops_0_br_mask) == 20'h0 & ~(io_flush & uops_0_uses_ldq));
      valids_1 <= ~(do_deq & deq_ptr_value == 2'h1) & (_GEN_10 | valids_1 & (io_brupdate_b1_mispredict_mask & uops_1_br_mask) == 20'h0 & ~(io_flush & uops_1_uses_ldq));
      valids_2 <= ~(do_deq & deq_ptr_value == 2'h2) & (_GEN_12 | valids_2 & (io_brupdate_b1_mispredict_mask & uops_2_br_mask) == 20'h0 & ~(io_flush & uops_2_uses_ldq));
      valids_3 <= ~(do_deq & (&deq_ptr_value)) & (_GEN_13 | valids_3 & (io_brupdate_b1_mispredict_mask & uops_3_br_mask) == 20'h0 & ~(io_flush & uops_3_uses_ldq));
      if (do_enq)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        enq_ptr_value <= enq_ptr_value + 2'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      if (do_deq)
        deq_ptr_value <= deq_ptr_value + 2'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      if (~(do_enq == do_deq))
        maybe_full <= do_enq;
    end
    uops_0_br_mask <= do_enq & _GEN_7 ? _uops_br_mask_T_1 : ({20{~valids_0}} | ~io_brupdate_b1_resolve_mask) & uops_0_br_mask;
    if (_GEN_8) begin
      uops_0_ldq_idx <= io_enq_bits_uop_ldq_idx;
      uops_0_stq_idx <= io_enq_bits_uop_stq_idx;
      uops_0_is_amo <= io_enq_bits_uop_is_amo;
      uops_0_uses_ldq <= io_enq_bits_uop_uses_ldq;
      uops_0_uses_stq <= io_enq_bits_uop_uses_stq;
    end
    uops_1_br_mask <= do_enq & _GEN_9 ? _uops_br_mask_T_1 : ({20{~valids_1}} | ~io_brupdate_b1_resolve_mask) & uops_1_br_mask;
    if (_GEN_10) begin
      uops_1_ldq_idx <= io_enq_bits_uop_ldq_idx;
      uops_1_stq_idx <= io_enq_bits_uop_stq_idx;
      uops_1_is_amo <= io_enq_bits_uop_is_amo;
      uops_1_uses_ldq <= io_enq_bits_uop_uses_ldq;
      uops_1_uses_stq <= io_enq_bits_uop_uses_stq;
    end
    uops_2_br_mask <= do_enq & _GEN_11 ? _uops_br_mask_T_1 : ({20{~valids_2}} | ~io_brupdate_b1_resolve_mask) & uops_2_br_mask;
    if (_GEN_12) begin
      uops_2_ldq_idx <= io_enq_bits_uop_ldq_idx;
      uops_2_stq_idx <= io_enq_bits_uop_stq_idx;
      uops_2_is_amo <= io_enq_bits_uop_is_amo;
      uops_2_uses_ldq <= io_enq_bits_uop_uses_ldq;
      uops_2_uses_stq <= io_enq_bits_uop_uses_stq;
    end
    uops_3_br_mask <= do_enq & (&enq_ptr_value) ? _uops_br_mask_T_1 : ({20{~valids_3}} | ~io_brupdate_b1_resolve_mask) & uops_3_br_mask;
    if (_GEN_13) begin
      uops_3_ldq_idx <= io_enq_bits_uop_ldq_idx;
      uops_3_stq_idx <= io_enq_bits_uop_stq_idx;
      uops_3_is_amo <= io_enq_bits_uop_is_amo;
      uops_3_uses_ldq <= io_enq_bits_uop_uses_ldq;
      uops_3_uses_stq <= io_enq_bits_uop_uses_stq;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:52];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h35; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        valids_0 = _RANDOM[6'h0][0];
        valids_1 = _RANDOM[6'h0][1];
        valids_2 = _RANDOM[6'h0][2];
        valids_3 = _RANDOM[6'h0][3];
        uops_0_br_mask = _RANDOM[6'h5][20:1];
        uops_0_ldq_idx = _RANDOM[6'h7][19:15];
        uops_0_stq_idx = _RANDOM[6'h7][24:20];
        uops_0_is_amo = _RANDOM[6'hB][20];
        uops_0_uses_ldq = _RANDOM[6'hB][21];
        uops_0_uses_stq = _RANDOM[6'hB][22];
        uops_1_br_mask = _RANDOM[6'h12][22:3];
        uops_1_ldq_idx = _RANDOM[6'h14][21:17];
        uops_1_stq_idx = _RANDOM[6'h14][26:22];
        uops_1_is_amo = _RANDOM[6'h18][22];
        uops_1_uses_ldq = _RANDOM[6'h18][23];
        uops_1_uses_stq = _RANDOM[6'h18][24];
        uops_2_br_mask = _RANDOM[6'h1F][24:5];
        uops_2_ldq_idx = _RANDOM[6'h21][23:19];
        uops_2_stq_idx = _RANDOM[6'h21][28:24];
        uops_2_is_amo = _RANDOM[6'h25][24];
        uops_2_uses_ldq = _RANDOM[6'h25][25];
        uops_2_uses_stq = _RANDOM[6'h25][26];
        uops_3_br_mask = _RANDOM[6'h2C][26:7];
        uops_3_ldq_idx = _RANDOM[6'h2E][25:21];
        uops_3_stq_idx = _RANDOM[6'h2E][30:26];
        uops_3_is_amo = _RANDOM[6'h32][26];
        uops_3_uses_ldq = _RANDOM[6'h32][27];
        uops_3_uses_stq = _RANDOM[6'h32][28];
        enq_ptr_value = _RANDOM[6'h34][13:12];
        deq_ptr_value = _RANDOM[6'h34][15:14];
        maybe_full = _RANDOM[6'h34][16];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_4x65 ram_ext (
    .R0_addr (deq_ptr_value),	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (enq_ptr_value),	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
    .W0_en   (do_enq),	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .W0_clk  (clock),
    .W0_data ({io_enq_bits_is_hella, io_enq_bits_data})
  );
  assign io_enq_ready = ~full;
  assign io_deq_valid = ~io_empty & _GEN_0 & (io_brupdate_b1_mispredict_mask & out_uop_br_mask) == 20'h0 & ~(io_flush & out_uop_uses_ldq);
  assign io_deq_bits_uop_br_mask = out_uop_br_mask & ~io_brupdate_b1_resolve_mask;
  assign io_deq_bits_uop_ldq_idx = _GEN_2[deq_ptr_value];
  assign io_deq_bits_uop_stq_idx = _GEN_3[deq_ptr_value];
  assign io_deq_bits_uop_is_amo = _GEN_4[deq_ptr_value];
  assign io_deq_bits_uop_uses_ldq = out_uop_uses_ldq;
  assign io_deq_bits_uop_uses_stq = _GEN_6[deq_ptr_value];
  assign io_deq_bits_data = _ram_ext_R0_data[63:0];
  assign io_deq_bits_is_hella = _ram_ext_R0_data[64];
endmodule

