// Generated by CIRCT unknown git version

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module FPU(
  input         clock,
  input         reset,
  input         io_req_valid,
  input  [6:0]  io_req_bits_uop_uopc,
  input  [19:0] io_req_bits_uop_imm_packed,
  input  [64:0] io_req_bits_rs1_data,
  input  [64:0] io_req_bits_rs2_data,
  input  [64:0] io_req_bits_rs3_data,
  input  [2:0]  io_req_bits_fcsr_rm,
  output [64:0] io_resp_bits_data,
  output        io_resp_bits_fflags_valid,
  output [4:0]  io_resp_bits_fflags_bits_flags
);

  wire        _fpmu_io_out_valid;
  wire [64:0] _fpmu_io_out_bits_data;
  wire [4:0]  _fpmu_io_out_bits_exc;
  wire        _fpiu_io_out_bits_lt;
  wire [63:0] _fpiu_io_out_bits_toint;
  wire [4:0]  _fpiu_io_out_bits_exc;
  wire [1:0]  _sfma_io_in_bits_fma_decoder_io_cmd;
  wire        _sfma_io_out_valid;
  wire [64:0] _sfma_io_out_bits_data;
  wire [4:0]  _sfma_io_out_bits_exc;
  wire [1:0]  _dfma_io_in_bits_fma_decoder_io_cmd;
  wire        _dfma_io_out_valid;
  wire [64:0] _dfma_io_out_bits_data;
  wire [4:0]  _dfma_io_out_bits_exc;
  wire        _fp_decoder_io_sigs_ren2;
  wire        _fp_decoder_io_sigs_ren3;
  wire        _fp_decoder_io_sigs_swap23;
  wire [1:0]  _fp_decoder_io_sigs_typeTagIn;
  wire [1:0]  _fp_decoder_io_sigs_typeTagOut;
  wire        _fp_decoder_io_sigs_toint;
  wire        _fp_decoder_io_sigs_fastpipe;
  wire        _fp_decoder_io_sigs_fma;
  wire        _fp_decoder_io_sigs_wflags;
  wire [2:0]  fp_rm = (&(io_req_bits_uop_imm_packed[2:0])) ? io_req_bits_fcsr_rm : io_req_bits_uop_imm_packed[2:0];
  wire        _sfma_io_in_valid_T = io_req_valid & _fp_decoder_io_sigs_fma;
  wire        _fpmu_double_T_1 = _fp_decoder_io_sigs_typeTagOut == 2'h1;
  wire [32:0] _sfma_io_in_bits_req_in2_T_1 = {io_req_bits_rs2_data[31], io_req_bits_rs2_data[52], io_req_bits_rs2_data[30:0]} | ((&(io_req_bits_rs2_data[64:60])) ? 33'h0 : 33'hE0400000);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :372:{26,31}]
  wire        fpiu_io_in_valid = io_req_valid & (_fp_decoder_io_sigs_toint | _fp_decoder_io_sigs_fastpipe & _fp_decoder_io_sigs_wflags);
  wire [2:0]  fpiu_io_in_bits_req_in1_prev_prev_expOut_expCode = {io_req_bits_rs1_data[52], io_req_bits_rs1_data[30:29]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :279:26, :358:14]
  wire [11:0] _fpiu_io_in_bits_req_in1_prev_prev_expOut_commonCase_T_2 = {3'h0, io_req_bits_rs1_data[52], io_req_bits_rs1_data[30:23]} + 12'h700;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:{31,50}, :358:14]
  wire [64:0] fpmu_io_in_bits_in1 = _fp_decoder_io_sigs_typeTagIn[0] | (&(io_req_bits_rs1_data[64:60])) ? (_fp_decoder_io_sigs_typeTagIn[0] ? io_req_bits_rs1_data : {io_req_bits_rs1_data[31], fpiu_io_in_bits_req_in1_prev_prev_expOut_expCode == 3'h0 | fpiu_io_in_bits_req_in1_prev_prev_expOut_expCode > 3'h5 ? {io_req_bits_rs1_data[52], io_req_bits_rs1_data[30:29], _fpiu_io_in_bits_req_in1_prev_prev_expOut_commonCase_T_2[8:0]} : _fpiu_io_in_bits_req_in1_prev_prev_expOut_commonCase_T_2, io_req_bits_rs1_data[22:0], 29'h0}) : 65'hE008000000000000;
  wire [2:0]  fpiu_io_in_bits_req_in2_prev_prev_expOut_expCode = {io_req_bits_rs2_data[52], io_req_bits_rs2_data[30:29]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :279:26, :358:14]
  wire [11:0] _fpiu_io_in_bits_req_in2_prev_prev_expOut_commonCase_T_2 = {3'h0, io_req_bits_rs2_data[52], io_req_bits_rs2_data[30:23]} + 12'h700;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:{31,50}, :358:14]
  wire [64:0] fpmu_io_in_bits_in2 = _fp_decoder_io_sigs_typeTagIn[0] | (&(io_req_bits_rs2_data[64:60])) ? (_fp_decoder_io_sigs_typeTagIn[0] ? io_req_bits_rs2_data : {io_req_bits_rs2_data[31], fpiu_io_in_bits_req_in2_prev_prev_expOut_expCode == 3'h0 | fpiu_io_in_bits_req_in2_prev_prev_expOut_expCode > 3'h5 ? {io_req_bits_rs2_data[52], io_req_bits_rs2_data[30:29], _fpiu_io_in_bits_req_in2_prev_prev_expOut_commonCase_T_2[8:0]} : _fpiu_io_in_bits_req_in2_prev_prev_expOut_commonCase_T_2, io_req_bits_rs2_data[22:0], 29'h0}) : 65'hE008000000000000;
  reg         fpiu_out_REG;
  reg         fpiu_out_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
  reg  [63:0] fpiu_out_pipe_b_toint;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [4:0]  fpiu_out_pipe_b_exc;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg         fpiu_out_pipe_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
  reg  [63:0] fpiu_out_pipe_pipe_b_toint;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [4:0]  fpiu_out_pipe_pipe_b_exc;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg         fpiu_out_pipe_pipe_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
  reg  [63:0] fpiu_out_pipe_pipe_pipe_b_toint;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg  [4:0]  fpiu_out_pipe_pipe_pipe_b_exc;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  wire        fpmu_io_in_valid = io_req_valid & _fp_decoder_io_sigs_fastpipe;
  reg         fpmu_double_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
  reg         fpmu_double_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg         fpmu_double_pipe_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
  reg         fpmu_double_pipe_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg         fpmu_double_pipe_pipe_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
  reg         fpmu_double_pipe_pipe_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  reg         fpmu_double_pipe_pipe_pipe_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
  always @(posedge clock) begin
    fpiu_out_REG <= fpiu_io_in_valid & ~_fp_decoder_io_sigs_fastpipe;
    if (fpiu_out_REG) begin
      fpiu_out_pipe_b_toint <= _fpiu_io_out_bits_toint;
      fpiu_out_pipe_b_exc <= _fpiu_io_out_bits_exc;
    end
    if (fpiu_out_pipe_v) begin	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      fpiu_out_pipe_pipe_b_toint <= fpiu_out_pipe_b_toint;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      fpiu_out_pipe_pipe_b_exc <= fpiu_out_pipe_b_exc;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    end
    if (fpiu_out_pipe_pipe_v) begin	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      fpiu_out_pipe_pipe_pipe_b_toint <= fpiu_out_pipe_pipe_b_toint;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
      fpiu_out_pipe_pipe_pipe_b_exc <= fpiu_out_pipe_pipe_b_exc;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    end
    if (fpmu_io_in_valid)
      fpmu_double_pipe_b <= _fpmu_double_T_1;
    if (fpmu_double_pipe_v)	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      fpmu_double_pipe_pipe_b <= fpmu_double_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    if (fpmu_double_pipe_pipe_v)	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      fpmu_double_pipe_pipe_pipe_b <= fpmu_double_pipe_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    if (fpmu_double_pipe_pipe_pipe_v)	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      fpmu_double_pipe_pipe_pipe_pipe_b <= fpmu_double_pipe_pipe_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:142:26]
    if (reset) begin
      fpiu_out_pipe_v <= 1'h0;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      fpiu_out_pipe_pipe_v <= 1'h0;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      fpiu_out_pipe_pipe_pipe_v <= 1'h0;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      fpmu_double_pipe_v <= 1'h0;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      fpmu_double_pipe_pipe_v <= 1'h0;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      fpmu_double_pipe_pipe_pipe_v <= 1'h0;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
    end
    else begin
      fpiu_out_pipe_v <= fpiu_out_REG;
      fpiu_out_pipe_pipe_v <= fpiu_out_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      fpiu_out_pipe_pipe_pipe_v <= fpiu_out_pipe_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      fpmu_double_pipe_v <= fpmu_io_in_valid;
      fpmu_double_pipe_pipe_v <= fpmu_double_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
      fpmu_double_pipe_pipe_pipe_v <= fpmu_double_pipe_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:141:24]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:33];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h22; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        fpiu_out_REG = _RANDOM[6'h0][0];
        fpiu_out_pipe_v = _RANDOM[6'h0][1];
        fpiu_out_pipe_b_toint = {_RANDOM[6'h9][31:2], _RANDOM[6'hA], _RANDOM[6'hB][1:0]};
        fpiu_out_pipe_b_exc = _RANDOM[6'hB][6:2];
        fpiu_out_pipe_pipe_v = _RANDOM[6'hB][7];
        fpiu_out_pipe_pipe_b_toint = {_RANDOM[6'h14][31:8], _RANDOM[6'h15], _RANDOM[6'h16][7:0]};
        fpiu_out_pipe_pipe_b_exc = _RANDOM[6'h16][12:8];
        fpiu_out_pipe_pipe_pipe_v = _RANDOM[6'h16][13];
        fpiu_out_pipe_pipe_pipe_b_toint = {_RANDOM[6'h1F][31:14], _RANDOM[6'h20], _RANDOM[6'h21][13:0]};
        fpiu_out_pipe_pipe_pipe_b_exc = _RANDOM[6'h21][18:14];
        fpmu_double_pipe_v = _RANDOM[6'h21][19];
        fpmu_double_pipe_b = _RANDOM[6'h21][20];
        fpmu_double_pipe_pipe_v = _RANDOM[6'h21][21];
        fpmu_double_pipe_pipe_b = _RANDOM[6'h21][22];
        fpmu_double_pipe_pipe_pipe_v = _RANDOM[6'h21][23];
        fpmu_double_pipe_pipe_pipe_b = _RANDOM[6'h21][24];
        fpmu_double_pipe_pipe_pipe_pipe_b = _RANDOM[6'h21][26];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  UOPCodeFPUDecoder fp_decoder (
    .io_uopc            (io_req_bits_uop_uopc),
    .io_sigs_ren2       (_fp_decoder_io_sigs_ren2),
    .io_sigs_ren3       (_fp_decoder_io_sigs_ren3),
    .io_sigs_swap23     (_fp_decoder_io_sigs_swap23),
    .io_sigs_typeTagIn  (_fp_decoder_io_sigs_typeTagIn),
    .io_sigs_typeTagOut (_fp_decoder_io_sigs_typeTagOut),
    .io_sigs_fromint    (/* unused */),
    .io_sigs_toint      (_fp_decoder_io_sigs_toint),
    .io_sigs_fastpipe   (_fp_decoder_io_sigs_fastpipe),
    .io_sigs_fma        (_fp_decoder_io_sigs_fma),
    .io_sigs_wflags     (_fp_decoder_io_sigs_wflags)
  );
  FPUFMAPipe_l4_f64 dfma (
    .clock             (clock),
    .reset             (reset),
    .io_in_valid       (_sfma_io_in_valid_T & _fpmu_double_T_1),
    .io_in_bits_ren3   (_fp_decoder_io_sigs_ren3),
    .io_in_bits_swap23 (_fp_decoder_io_sigs_swap23),
    .io_in_bits_rm     (fp_rm),
    .io_in_bits_fmaCmd (_dfma_io_in_bits_fma_decoder_io_cmd),
    .io_in_bits_in1    (io_req_bits_rs1_data),
    .io_in_bits_in2    (io_req_bits_rs2_data),
    .io_in_bits_in3    (_fp_decoder_io_sigs_swap23 ? io_req_bits_rs2_data : io_req_bits_rs3_data),
    .io_out_valid      (_dfma_io_out_valid),
    .io_out_bits_data  (_dfma_io_out_bits_data),
    .io_out_bits_exc   (_dfma_io_out_bits_exc)
  );
  FMADecoder dfma_io_in_bits_fma_decoder (
    .io_uopc (io_req_bits_uop_uopc),
    .io_cmd  (_dfma_io_in_bits_fma_decoder_io_cmd)
  );
  FPUFMAPipe_l4_f32 sfma (
    .clock             (clock),
    .reset             (reset),
    .io_in_valid       (_sfma_io_in_valid_T & _fp_decoder_io_sigs_typeTagOut == 2'h0),
    .io_in_bits_ren3   (_fp_decoder_io_sigs_ren3),
    .io_in_bits_swap23 (_fp_decoder_io_sigs_swap23),
    .io_in_bits_rm     (fp_rm),
    .io_in_bits_fmaCmd (_sfma_io_in_bits_fma_decoder_io_cmd),
    .io_in_bits_in1    ({32'h0, {io_req_bits_rs1_data[31], io_req_bits_rs1_data[52], io_req_bits_rs1_data[30:0]} | ((&(io_req_bits_rs1_data[64:60])) ? 33'h0 : 33'hE0400000)}),
    .io_in_bits_in2    ({32'h0, _sfma_io_in_bits_req_in2_T_1}),
    .io_in_bits_in3    ({32'h0, _fp_decoder_io_sigs_swap23 ? _sfma_io_in_bits_req_in2_T_1 : {io_req_bits_rs3_data[31], io_req_bits_rs3_data[52], io_req_bits_rs3_data[30:0]} | ((&(io_req_bits_rs3_data[64:60])) ? 33'h0 : 33'hE0400000)}),
    .io_out_valid      (_sfma_io_out_valid),
    .io_out_bits_data  (_sfma_io_out_bits_data),
    .io_out_bits_exc   (_sfma_io_out_bits_exc)
  );
  FMADecoder sfma_io_in_bits_fma_decoder (
    .io_uopc (io_req_bits_uop_uopc),
    .io_cmd  (_sfma_io_in_bits_fma_decoder_io_cmd)
  );
  FPToInt fpiu (
    .clock                 (clock),
    .io_in_valid           (fpiu_io_in_valid),
    .io_in_bits_ren2       (_fp_decoder_io_sigs_ren2),
    .io_in_bits_typeTagOut (_fp_decoder_io_sigs_typeTagOut),
    .io_in_bits_wflags     (_fp_decoder_io_sigs_wflags),
    .io_in_bits_rm         (fp_rm),
    .io_in_bits_typ        (io_req_bits_uop_imm_packed[9:8]),
    .io_in_bits_fmt        (io_req_bits_uop_uopc == 7'h46 ? 2'h0 : {1'h0, |_fp_decoder_io_sigs_typeTagIn}),
    .io_in_bits_in1        (fpmu_io_in_bits_in1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10]
    .io_in_bits_in2        (fpmu_io_in_bits_in2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10]
    .io_out_bits_lt        (_fpiu_io_out_bits_lt),
    .io_out_bits_toint     (_fpiu_io_out_bits_toint),
    .io_out_bits_exc       (_fpiu_io_out_bits_exc)
  );
  FPToFP fpmu (
    .clock                 (clock),
    .reset                 (reset),
    .io_in_valid           (fpmu_io_in_valid),
    .io_in_bits_ren2       (_fp_decoder_io_sigs_ren2),
    .io_in_bits_typeTagOut (_fp_decoder_io_sigs_typeTagOut),
    .io_in_bits_wflags     (_fp_decoder_io_sigs_wflags),
    .io_in_bits_rm         (fp_rm),
    .io_in_bits_in1        (fpmu_io_in_bits_in1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10]
    .io_in_bits_in2        (fpmu_io_in_bits_in2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10]
    .io_out_valid          (_fpmu_io_out_valid),
    .io_out_bits_data      (_fpmu_io_out_bits_data),
    .io_out_bits_exc       (_fpmu_io_out_bits_exc),
    .io_lt                 (_fpiu_io_out_bits_lt)
  );
  assign io_resp_bits_data = _dfma_io_out_valid ? _dfma_io_out_bits_data : _sfma_io_out_valid ? {12'hFFF, _sfma_io_out_bits_data[31], 20'hFFFFF, _sfma_io_out_bits_data[32], _sfma_io_out_bits_data[30:0]} : fpiu_out_pipe_pipe_pipe_v ? {1'h0, fpiu_out_pipe_pipe_pipe_b_toint} : fpmu_double_pipe_pipe_pipe_pipe_b ? _fpmu_io_out_bits_data : {12'hFFF, _fpmu_io_out_bits_data[31], 20'hFFFFF, _fpmu_io_out_bits_data[32], _fpmu_io_out_bits_data[30:0]};
  assign io_resp_bits_fflags_valid = fpiu_out_pipe_pipe_pipe_v | _fpmu_io_out_valid | _sfma_io_out_valid | _dfma_io_out_valid;
  assign io_resp_bits_fflags_bits_flags = _dfma_io_out_valid ? _dfma_io_out_bits_exc : _sfma_io_out_valid ? _sfma_io_out_bits_exc : fpiu_out_pipe_pipe_pipe_v ? fpiu_out_pipe_pipe_pipe_b_exc : _fpmu_io_out_bits_exc;
endmodule

