// Generated by CIRCT unknown git version
module ghist_0(
  input  [5:0]  R0_addr,
  input         R0_clk,
  output [71:0] R0_data,
  input  [5:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [71:0] W0_data
);

  ghist_0_ext ghist_0_ext (
    .R0_addr (R0_addr),
    .R0_en   (1'h1),
    .R0_clk  (R0_clk),
    .R0_data (R0_data),
    .W0_addr (W0_addr),
    .W0_en   (W0_en),
    .W0_clk  (W0_clk),
    .W0_data (W0_data)
  );
endmodule

