// Generated by CIRCT unknown git version
// VCS coverage exclude_file
module lb_32x128(
  input  [4:0]   R0_addr,
  input          R0_en,
  input          R0_clk,
  output [127:0] R0_data,
  input  [4:0]   W0_addr,
  input          W0_en,
  input          W0_clk,
  input  [127:0] W0_data
);

  reg [127:0] Memory[0:31];
  always @(posedge W0_clk) begin
    if (W0_en & 1'h1)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_
    reg [127:0] _RANDOM_MEM;
    initial begin
      `INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_MEM_INIT
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          for (logic [7:0] j = 8'h0; j < 8'h80; j += 8'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;
          end
          Memory[i[4:0]] = _RANDOM_MEM;
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 128'bx;
endmodule

