// Generated by CIRCT unknown git version
// VCS coverage exclude_file
module ram_16x46(
  input  [3:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [45:0] R0_data,
  input  [3:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [45:0] W0_data
);

  reg [45:0] Memory[0:15];
  always @(posedge W0_clk) begin
    if (W0_en & 1'h1)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_
    reg [63:0] _RANDOM_MEM;
    initial begin
      `INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_MEM_INIT
        for (logic [4:0] i = 5'h0; i < 5'h10; i += 5'h1) begin
          for (logic [6:0] j = 7'h0; j < 7'h40; j += 7'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;
          end
          Memory[i[3:0]] = _RANDOM_MEM[45:0];
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 46'bx;
endmodule

