// Generated by CIRCT unknown git version
module table_0(
  input  [6:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [43:0] R0_data,
  input  [6:0]  W0_addr,
  input         W0_clk,
  input  [43:0] W0_data,
  input  [3:0]  W0_mask
);

  table_ext table_ext (
    .R0_addr (R0_addr),
    .R0_en   (R0_en),
    .R0_clk  (R0_clk),
    .R0_data (R0_data),
    .W0_addr (W0_addr),
    .W0_en   (1'h1),
    .W0_clk  (W0_clk),
    .W0_data (W0_data),
    .W0_mask (W0_mask)
  );
endmodule

