// Generated by CIRCT unknown git version
module UOPCodeFDivDecoder(
  input  [6:0] io_uopc,
  output [1:0] io_sigs_typeTagIn,
  output       io_sigs_div,
  output       io_sigs_sqrt
);

  wire [4:0] decoder_decoded_invInputs = ~(io_uopc[4:0]);
  wire [6:0] _decoder_decoded_andMatrixOutputs_T_1 = {decoder_decoded_invInputs[0], io_uopc[1], io_uopc[2], decoder_decoded_invInputs[3], decoder_decoded_invInputs[4], io_uopc[5], io_uopc[6]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [3:0] _decoder_decoded_andMatrixOutputs_T_3 = {io_uopc[3], decoder_decoded_invInputs[4], io_uopc[5], io_uopc[6]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  assign io_sigs_typeTagIn = {1'h0, |{&_decoder_decoded_andMatrixOutputs_T_1, &_decoder_decoded_andMatrixOutputs_T_3}};
  assign io_sigs_div = |{&{decoder_decoded_invInputs[1], io_uopc[2], decoder_decoded_invInputs[3], decoder_decoded_invInputs[4], io_uopc[5], io_uopc[6]}, &_decoder_decoded_andMatrixOutputs_T_1};
  assign io_sigs_sqrt = |{&{io_uopc[0], io_uopc[1], io_uopc[2], decoder_decoded_invInputs[3], decoder_decoded_invInputs[4], io_uopc[5], io_uopc[6]}, &_decoder_decoded_andMatrixOutputs_T_3};
endmodule

